# Generated by Django 3.1.4 on 2021-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_userinroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='video_id',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='end',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
